name: build-eadp-airflow-docker-images

on:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - image: trivadis/llm-graph-builder-backend
            dockerfile: backend/Dockerfile
            context_dir: backend           
            tag: latest
          - image: trivadis/llm-graph-builder-frontend
            dockerfile: frontend/Dockerfile
            context_dir: frontend
            tag: latest
            build_args:
              - VITE_BACKEND_API_URL=http://localhost:28414
              - VITE_REACT_APP_SOURCES=local,youtube,wiki,s3,web            
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      -
        # Add support for more platforms with QEMU (optional)
        # https://github.com/docker/setup-qemu-action
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3        
      - name: Setup Docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{matrix.image}}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.context_dir }}
          file: ${{ matrix.dockerfile }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ matrix.image }}:${{ matrix.tag }}
          build-args: ${{ toJson(matrix.build_args) }}
